# Generated by Django 5.1.7 on 2025-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_guestlist_guest_remove_guestlist_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
