# Generated by Django 5.1.7 on 2025-03-26 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rsvp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="hosted_by",
        ),
        migrations.AddField(
            model_name="event",
            name="hosted_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
