# Generated by Django 5.1.7 on 2025-03-26 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_event_rsvp_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rsvp",
            name="status",
        ),
    ]
