# Generated by Django 5.1.7 on 2025-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_eventimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_event.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
        migrations.DeleteModel(
            name="EventImage",
        ),
    ]
