# Generated by Django 5.1.7 on 2025-03-31 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_event_image_delete_eventimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="rsvp",
            name="created_at",
        ),
        migrations.AddField(
            model_name="rsvp",
            name="status",
            field=models.CharField(
                choices=[
                    ("going", "Going"),
                    ("maybe", "Maybe"),
                    ("not_going", "Not Going"),
                ],
                default="going",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="event_images/default_event.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
        migrations.CreateModel(
            name="GuestList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("attending", "Attending"),
                            ("declined", "Declined"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_list",
                        to="api.event",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.guest"
                    ),
                ),
            ],
        ),
    ]
