# Generated by Django 5.1.7 on 2025-04-02 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_event_rsvp_users_alter_rsvp_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestlist",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="guestlist",
            name="event",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="GuestList",
        ),
    ]
