# Generated by Django 5.1.7 on 2025-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_event_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                    ("premium_user", "Premium User"),
                ],
                default="guest",
                max_length=15,
            ),
        ),
    ]
