# Generated by Django 5.1.7 on 2025-04-02 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_customuser_is_subscribed_customuser_subscription_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_subscribed",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_end",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_start",
        ),
    ]
