version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: taskdef.json 
        LoadBalancerInfo:
          ContainerName: "simple-docker-service-06d0c0bbe761"
          ContainerPort: 8000